spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=E3zYWBhYkzVcJjU/c7QQ1BVKqTRkXRqJVlgHaxtwqyY=

# Opcional: comportamiento de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Desactiva la creación automática de Hibernate
spring.jpa.hibernate.ddl-auto=none

# Indica que use los archivos schema.sql y data.sql
spring.sql.init.mode=always

