spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

aws.accessKeyId=${MY_AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${MY_AWS_SECRET_ACCESS_KEY}

spring.security.oauth2.client.registration.cognito.region=${COGNITO_REGION}
spring.security.oauth2.client.registration.cognito.userPoolId=${COGNITO_USER_POOL_ID}
spring.security.oauth2.client.registration.cognito.client-id=${COGNITO_CLIENT_ID}
spring.security.oauth2.client.registration.cognito.client-secret=${COGNITO_CLIENT_SECRET}
spring.security.oauth2.client.registration.cognito.scope=openid,email,phone
spring.security.oauth2.client.registration.cognito.redirect-uri=https://d84l1y8p4kdic.cloudfront.net
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI}

spring.security.oauth2.client.provider.cognito.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_lTSWlzRlA
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_lTSWlzRlA
spring.security.oauth2.client.provider.cognito.user-name-attribute=username

jwt.secret=E3zYWBhYkzVcJjU/c7QQ1BVKqTRkXRqJVlgHaxtwqyY=

# Opcional: comportamiento de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Indica que use los archivos schema.sql y data.sql

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=30000

# API versioning - Removido context-path para manejar versionado manual
# server.servlet.context-path=/api/v1

