CREATE TABLE IF NOT EXISTS libros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor VARCHAR(255),
    categoria VARCHAR(255),
    descripcion VARCHAR(1000),
    paginas INTEGER,
    titulo VARCHAR(255),
    url_archivo VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS book_etiquetas (
    book_id BIGINT NOT NULL,
    etiquetas VARCHAR(255),
    CONSTRAINT FKrwydpbn585t9wfrjv1fm1chkt FOREIGN KEY (book_id) REFERENCES libros
);

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255),
    email VARCHAR(255),
    contrasena VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS user_categorias_preferidas (
    user_id BIGINT NOT NULL,
    categorias_preferidas VARCHAR(255),
    CONSTRAINT FK57r01cf1pejlc1lkj23rpuiu5 FOREIGN KEY (user_id) REFERENCES usuarios
);
